spring:
  datasource:
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PWD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  port: ${PORT}
  http2:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}

discord:
  oauth:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    token-endpoint: https://discord.com/api/oauth2/token
    tokenRevokeEndpoint: https://discord.com/api/oauth2/token/revoke
    userInfoEnpoint: https://discord.com/api/users/@me

springdoc:
  paths-to-match: /api/v2/**